version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./client/.env

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_data:

networks:
  default:
    driver: bridge
