syntax = "proto3";

package attachment;

import "common.proto";

service AttachmentService {
  rpc ListByTask(ListByTaskRequest) returns (ListByTaskResponse);
  rpc UploadFileToTask(UploadFileRequest) returns (UploadFileResponse);
  rpc DownloadById(DownloadByIdRequest) returns (DownloadFileResponse);
  rpc DeleteById(DeleteByIdRequest) returns (common.Empty);
}

message ListByTaskRequest {
  string taskId = 1;
}

message ListByTaskResponse {
  repeated AttachmentFull attachments = 1;
}

message AttachmentFull {
  string id = 1;
  string taskId = 2;
  string projectId = 3;
  string originalName = 4;
  string mimeType = 5;
  int64 size = 6;
  string storagePath = 7;
  string uploadedBy = 8;
  string createdAt = 9;
}

message UploadFileRequest {
  string taskId = 1;
  string originalName = 2;
  string mimeType = 3;
  bytes data = 4;
}

message UploadFileResponse {
  repeated common.Attachment attachments = 1;
}

message DownloadByIdRequest {
  string id = 1;
}

message DownloadFileResponse {
  DownloadMetadata metadata = 1;
  bytes data = 2;
}

message DownloadMetadata {
  string originalName = 1;
  string mimeType = 2;
  int64 size = 3;
}

message DeleteByIdRequest {
  string id = 1;
}